server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route 路由的id，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          filters:
#            - AddRequestPatameter=X-Request-Id,1024 #过滤工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由
            - After=2021-02-21T20:05:42.792+08:00[Asia/Shanghai]
#            - Cookie=username,lgz
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Method=GET

        - id: payment_routh2 #payment_eroute 路由的id，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/feign/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
    # 服务提供者provider注册进eureka服务列表内
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
